# This workflow will build a .NET project, using the GitHub .NET workflow template
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET GitHub Workflow Template on main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./LIMinimalApiDemo/LIMinimalApiDemo.sln
    - name: Build
      run: dotnet build --no-restore ./LIMinimalApiDemo/LIMinimalApiDemo.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
